### PR TITLE
Version 1.19.0

### PR DESCRIPTION
**Pull request by medyo**
- Add Share feature
- Migrate to Vite
- Speed up the App load

### CODE REVIEW

**Comment by medyo** [comment]
@idebenone I've tweaked your share Modal, check the new version

**Comment by idebenone** [comment]
Hey @medyo 

Im getting this error : 
image

I even cloned from the main repo and tried, same error in both cases.
How can I resolve this?

Node Version : Tried on both Node ~16 and ~20

**Comment by medyo** [comment]
@idebenone create an `.env` with the following vars:
```
VITE_BUILD_TARGET=extension
VITE_API_URL=https://api.hackertab.dev/
```

**Comment by idebenone** [comment]
@medyo 
Are we missing anything else?

**Comment by medyo** [comment]
@idebenone which adblock extension are you using?
can you also join a screenshot of the conflict happening between hackertab and the adblocker?

**Pull request merged**
