### PR TITLE
Enables tab navigation

### LINKED ISSUE #170: Enable tab navigation
I can't navigate the site using the keyboard.

**Ask**
Improve accessibility by allowing users to navigate the site using the keyboard more specifically tab navigation.

### PR DESCRIPTION
**Pull request by victor-duarte**
Closes #170

### Updates
- Enables tab navigation
  - Tweaks bookmarks icons interaction to allow smooth tab navigation
  - Updates html tag for better semantics and a11y purposes allowing tab navigation
  - Uses default browser outline behavior
- Display bookmarks cta on small devices to allow user to save bookmark (on large viewports it displays on card hover or focus of the cta)
- Update `aria-labels` on some elements for a11y purposes
- Removed unneeded tags an inline styles
- Minor alignment updates on small viewports (specifically for devices layout layout in `AppContentLayout.tsx`) complementing work on #169

### CODE REVIEW

**Comment by medyo** [comment]
Hi @victor-duarte,

Great contribution. I have a couple of comments:

The moon icon appears too bright against a light background
image

**Card Header**: Could you remove the excess horizontal margins between the title and dropdown?
image

**Comment by victor-duarte** [comment]
@medyo an update has been pushed:

- Moon icon brightness adjustment, also change to use the filled icon which seems to work better with the siblings
(after / before)
image

- Reduced block header vertical space by 10px from 54px to 44px.
(after / before)
image

**Comment by medyo** [comment]
> * Reduced block header vertical space by 10px from 54px to 44px.

I was talking about the horizontal space, between the title the dropdown (in red)

image

**Comment by victor-duarte** [comment]
doh

- Updated the space between the items and alignment
- height reverted to `54px`

image

**Pull request merged**
