### PR TITLE
added short links to easy access your favorite pages

### PR DESCRIPTION
**Pull request by quantumass**
Added short links so you can easily access favorite  pages.
The user can add/delete them as he wants

### CODE REVIEW

**Comment by medyo** [comment]
Interesting feature. thank you @quantumass 

We were discussing a way to add it without overwhelming the UI.
Screen Shot 2022-07-31 at 14 00 56

The current UI looks a bit similar to the tags which will definitely confuse users, 
Also, I don't think having like 6 or 7 websites will fit there. 
I prefer the "icons version" where each website is represented by its favicon that has a fixed size instead of a long text.
What do you think?

**Comment by quantumass** [comment]
@medyo great i will work on it

**Comment by medyo** [comment]
You can also rely on the Chrome API to get/set user bookmarks, so the user doesn't have to re-add his bookmarks manually.

**Comment by quantumass** [comment]
@medyo ok I grabbed the favicon of the url from DuckDuckGO and I added chrome bookmark API to get the already bookmarked links

**Comment by medyo** [comment]
I'll close this for now, but once we scheduled a release of the feature, I'll let you know

**Pull request closed without merging**
