### PR TITLE
Add Phind search engine

### PR DESCRIPTION
**Pull request by MustCodeAl**
adding phind.com

### CODE REVIEW

**Review by medyo — CHANGES_REQUESTED** [review]
The logo should appear in white when using the `Dark Mode`
Can you handle it using css only. Something like

```
.dark .searchEngineLogo {
  fill: white;
}
```
image

**Comment by MustCodeAl** [comment]
is this ok to put in app.css?

```
.dark .phindLogo {
  fill: white;
}
```

**Comment by medyo** [comment]
> is this ok to put in app.css?
> 
> ```
> .dark .phindLogo {
>   fill: white;
> }
> ```

Yes, that's okay, can you rename the class to be more generic so it can be used for the Yahoo logo too as it has the same UI issue?

**Review by MustCodeAl — COMMENTED** [review]
made the class more generic

**Comment by medyo** [comment]
Thanks @MustCodeAl for your contribution

**Pull request merged**
