### PR TITLE
Version 1.12.0

### LINKED ISSUE #78: New tab stops responding & slowing down the Firefox
Actually, this problem did not exist a few weeks ago. Somehow, every _X_ new tab open, the following case occurs:

Screen Shot 2021-11-29 at 09 22 02

Disabling the expansion fixes the issue.

```
Hackertab.dev 1.11.1
Firefox 94.0.2
macOS 11
```

My configuration:

Screen Shot 2021-11-29 at 10 47 23

Any ideas?

### LINKED ISSUE #79: DEV tab only works with a single language
If I remove the language options from the top of the new tab (hackertab) page, the DEV tab is empty. If I add more than one language to my settings, only the first one is reflected in the data retrieved from DEV. This is reflected in the code for the DEV service only accepting a single language tag. There's no indication why no data is displayed if I remove all languages from my interests, and there's no way to choose what I want to see from DEV (unlike the GitHub column).

### PR DESCRIPTION
**Pull request by medyo**
- Add the Language selector to the cards: Devto and Hashnode (closes #79)
- Limit the count of returned items when the the `My languages` item is selected (closes #78)

### CODE REVIEW

**Comment by medyo** [comment]
@Dentrax can you give a try to this version before deploying it
I hope it solves the slowing issue in Firefox

**Comment by Dentrax** [comment]
> @Dentrax can you give a try to this version before deploying it I hope it solves the slowing issue in Firefox

Sure! Never compiled an extension from source before. What should I do to deploy on Firefox?

**Comment by medyo** [comment]
You clone the project then
- git checkout develop
- yarn
- yarn start
- a new browser window will pop

Please follow the same tags and select the same cards as you did before and check if the slowness is still there.
That's it,
Thanks

**Comment by Dentrax** [comment]
Thanks, @medyo! I didn't see the [Development](https://github.com/medyo/hackertab.dev#development) section in the README. 🙈 

---

I tried this a bit while and _endless loop_ case didn't occur. But I don't take any responsibilities JFYI. :D

**Pull request merged**
